# Generated by Django 3.2.4 on 2021-06-26 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description for your account.', max_length=200)),
                ('number', models.CharField(help_text='Insert your account number here.', max_length=20)),
                ('balance', models.FloatField(default=0, help_text='Insert your initial baçance.')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
